name: FastAPI Docker Build and Push
on:
  push:
    branches:
      - main
jobs:
  myjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print a greeting
        run: echo 'Longquiz'
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build docker
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Build and push Docker image
        run: |
          docker buildx create --use
          docker buildx build \
            --file Dockerfile \
            --tag deepaksimon/longquiz:latest \
            --push .
